USE [master]
GO

/****** Object:  Database [Arvuyot]    Script Date: 19/07/2019 17:42:51 ******/
CREATE DATABASE [Arvuyot]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Arvuyot', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Arvuyot.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Arvuyot_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Arvuyot_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Arvuyot] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Arvuyot].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Arvuyot] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Arvuyot] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Arvuyot] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Arvuyot] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Arvuyot] SET ARITHABORT OFF 
GO

ALTER DATABASE [Arvuyot] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Arvuyot] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Arvuyot] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Arvuyot] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Arvuyot] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [Arvuyot] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Arvuyot] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Arvuyot] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Arvuyot] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Arvuyot] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Arvuyot] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Arvuyot] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Arvuyot] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Arvuyot] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Arvuyot] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Arvuyot] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Arvuyot] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Arvuyot] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Arvuyot] SET  MULTI_USER 
GO

ALTER DATABASE [Arvuyot] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Arvuyot] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Arvuyot] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Arvuyot] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Arvuyot] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Arvuyot] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Arvuyot] SET  READ_WRITE 
GO

